### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by yanwangoakland** [ros-planning/moveit_grasps#6]
Hello,

I cloned moveit_grasp packages from source for kinetic_devel version and the code compile successfully. But when I launch the command "roslaunch moveit_grasps test_grasp_generator.launch"
There is an error  [here](https://github.com/yanwangoakland/yanwang/blob/master/Launch%20Error.txt) 

Can you give me some suggestion?

My operating system is Ubuntu 16.04, ROS version is kinetic.

 I just installed the Baxter SDK and Simulator from Rethink Robotic official site, I want to know it is necessary  to install [baxter_cpp](https://github.com/davetcoleman/baxter_cpp) in order to launch the moveit_grasps package?

Thank You!

**Comment by Ridhwanluthra** [comment]
The kinetic-devel branch has a couple places where it is hardcoded for jaco robot.
you can refer to [this issue](https://github.com/davetcoleman/moveit_grasps/issues/2) which mentions what all you would need to update to get it working with your robot.
you can also take a look at [this PR](https://github.com/davetcoleman/moveit_grasps/pull/5) where I am making an effort to generalise it.

**Comment by yanwangoakland** [comment]
Thank you so much! 

I will try your method.

**Comment by yanwangoakland** [comment]
@Ridhwanluthra 
Hi, I'm very appreciate to your response for my problem.  But I have some problems  about your method.

1. As you said, I need to update my robot to get the code working base on [this issue](https://github.com/davetcoleman/moveit_grasps/issues/2).  Can you tell me some detail information how should I update my robot? The robot model I used is baxter with electrical grippers. 

2. I found you have changed many files in this package.  I want to know whether I need change all these files in my computer follow your work?

3.  I do not know whether you install the  [baxter_cpp](https://github.com/davetcoleman/baxter_cpp) . I just installed the Baxter SDK and Simulator from Rethink Robotic official site, I want to know it is necessary to install [baxter_cpp](https://github.com/davetcoleman/baxter_cpp) in order to launch the moveit_grasps package?

4.  I launched the command "roslaunch moveit_grasps rviz.launch",  it launched successfully, but I have see nothing in RVIZ. 

Can you give me some suggestion?

Thank You!

**Comment by Ridhwanluthra** [comment]
> 1. As you said, I need to update my robot to get the code working base on this issue. Can you tell me some detail information how should I update my robot? The robot model I used is baxter with electrical grippers.

I am not entirely sure if I can give you specific baxter info I will give you general details on the generalisations needed.
in grasp_data:
* you need to update the name of joint [here](https://github.com/davetcoleman/moveit_grasps/blob/kinetic-devel/src/grasp_data.cpp#L277)
* You need to create a way to set joint positions using distance between fingers [here](https://github.com/davetcoleman/moveit_grasps/blob/kinetic-devel/src/grasp_data.cpp#L233)

in grasp_generator:
* just manually set the pre grasp approach and post-retreat for the kind of grasps you wanna make.

in grasp_generator test:
* you need to set ideal pose for the grasp you wanna make.

In my code, I have generalised everything except [joint position setting](https://github.com/davetcoleman/moveit_grasps/issues/7).
if you plan to you use that, it can only has the grasp generator working.

> I found you have changed many files in this package. I want to know whether I need change all these files in my computer follow your work?

No, you just need to change what i mentioned above and then maybe if there is something wrong. keep in mind this is a devel package.

> I do not know whether you install the baxter_cpp . I just installed the Baxter SDK and Simulator from Rethink Robotic official site, I want to know it is necessary to install baxter_cpp in order to launch the moveit_grasps package?

I am not sure, but as far as MoveIt! is concerned it only needs the baxter_moveit_config. Also, from a small look at baxter_cpp I think that package implements the complete pick place functionality using this or some other generator.

> I launched the command "roslaunch moveit_grasps rviz.launch", it launched successfully, but I have see nothing in RVIZ.

That is  because that launch is responsible to only launch rviz and set up some static transforms

I hope this clears things up.
feel free to get back

**Comment by davetcoleman** [comment]
@mlautman and just now myself have cleaned up and tested the demos. Closing this old issue.
